name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tcl8.6 tcllib expect
      
    - name: Make
      run: make
      
    - name: Make Install
      run: make install
